[build]
  command = "pip install -r requirements.txt"
  publish = "."    # Publish from the repository root
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/wsgi_handler"
  status = 200
