[build]
  command = "pip install -r requirements.txt"
  publish = "build"  # or leave it blank if you have no static files
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/wsgi_handler"
  status = 200
